---
name: Local Config
version: 1.0.0
schema: v1

models:
  - name: Qwen2.5-Coder
    provider: ollama
    model: qwen2.5-coder:7b-instruct-q5_K_M
    roles:
      - chat
      - edit
      - apply
      - autocomplete

  - name: Nomic-Embed
    provider: ollama
    model: nomic-embed-text
    roles:
      - embed
      - rerank
